# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools
    - name: Build
      run: |
        python setup.py sdist
    - name: github-action-publish-binaries
      # You may pin to the exact commit or the version.
      # uses: skx/github-action-publish-binaries@75ce5546020fc1848da842f40240f9fa03e7a3a8
      uses: skx/github-action-publish-binaries@release-0.14
      with:
        # The pattern of files to upload
        args: dist/*

